name: Update Flake Inputs

on:
  schedule:
    # Run weekly on Sunday at 4:00 AM UTC
    - cron: "0 4 * * 0"
  workflow_dispatch:
  repository_dispatch:

jobs:
  update-flake-inputs:
    runs-on: nix
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update flake inputs
        uses: Mic92/update-flake-inputs-gitea@main
        with:
          auto-merge: true
          gitea-token: ${{ secrets.CI_BOT_TOKEN }}
          github-token: ${{ secrets.CI_BOT_GITHUB_TOKEN }}
